### ISSUE TITLE
Playstore download failed

### ISSUE THREAD

**Issue by Freepony** [sn-00-x/fakestore2playstore#4]
Magisk fails to download patched playstore. Is the server down?

![Screenshot_20220609-131155_Magisk](https://user-images.githubusercontent.com/23488067/172826907-5a0cbe9c-f202-4bf6-9d52-bbbfcf19ed9a.png)

**Comment by sn-00-x** [comment]
TLDR: Fixed

The wget version that ships with the busybox provided by Magisk 24 somehow can't download the patched playstore from Nanolx's repository. The server closes the connection because of a tls error. Now the patched playstore is included in this module and a download isn't required any more.
